const inquirer = require("inquirer");

const db = require("../db");

const viewItems = async (tableName) => {
	try {
		const table = db.getTable(tableName);

		const questions = [
			{
				type: "list",
				name: "viewMode",
				message: `How would you like to view ${tableName}?`,
				choices: () => {
					const choices = [{ name: "View-All", value: { group: false } }];
					const columnsArray = table.getColumnsArray();

					columnsArray.forEach((column) => {
						if (column.linkedName != undefined) {
							choices.push({ name: `View-By ${column.linkedName}`, value: { group: true, column } })
						}
					});

					return choices;
				},
			},
			{
				// only ask when grouping is enabled
				when: (answers) => { return answers.viewMode.group },
				type: "list",
				name: "columnMatch",
				message: (answers) => { return `View ${tableName} with which ${answers.viewMode.column.linkedName}?` },
				choices: (answers) => {
					// return array of elements from linked table
					return answers.viewMode.column.getChoices();
				},
			}
		];

		const answers = await inquirer.prompt(questions);
		// if items are to be grouped
		if (answers.viewMode.group) {
			const column = answers.viewMode.column;
			// filter items
			displayItems = table.getItemsArray().filter((item) => { return item[column.name] === answers.columnMatch })

			if (displayItems.length === 0) {
				console.log(`No ${tableName} with ${column.linkedName} ${column.getValue(answers.columnMatch)[column.linkedName]}`)
			} else {
				console.table(tableName, table.getLinkedArray(displayItems));
			}
		}
		// if items are not to be grouped
		else {
			let displayItems = table.getItemsArray();

			if (displayItems.length === 0) {
				console.log(`No ${tableName} to display`)
			} else {
				console.table(tableName, table.getLinkedArray(displayItems));
			}
		}

		// console.log(answers);
	} catch (err) {
		throw err;
	}
}

const addItem = async (tableName) => {
	try {
		const table = db.getTable(tableName);
		const columns = table.getColumns();

		// generate questions for table
		const questions = [];
		for (const name in columns) {
			const column = columns[name];
			const question = { name: name };

			question.message = `enter ${table.getName()} ${name}`;

			// add columns that have one property (name)
			if (Object.keys(column).length === 1) {
				question.type = "input";
			};
			// add columns with property "getChoices"
			if (Object.keys(column).includes("getChoices")) {
				question.type = "list";
				question.choices = column.getChoices;
			};

			if (!column.autoGenerate) questions.push(question);
		};

		const answers = await inquirer.prompt(questions);

		await table.addItem(answers);

		await table.displayItems();
	} catch (err) {
		throw err;
	}
};

const updateItem = async (tableName) => {
	try {
		const table = db.getTable(tableName);

		const questions = [
			{
				// ask which data item to modify
				type: "list",
				name: "item",
				message: `Which ${tableName.slice(0, -1)} to modify?`,
				choices: () => {
					return table.getItemsArray().map((item) => {
						let combinedName;
						if (item.hasOwnProperty("name")) {
							combinedName = item.name;
						} else {
							combinedName = `${item.first_name} ${item.last_name}`;
						}
						return { name: combinedName, value: item }
					});
				}
			},
			{
				// ask which column to modify
				type: "list",
				name: "column",
				message: `Which element to modify?`,
				choices: (answers) => {
					// create array from values of columns
					const choice = table.getColumnsArray().map((column) => {
						// null autogenerated columns
						if (column.autoGenerate) return null;

						// check for id links and replace values
						if (column.linkedName != undefined) {
							// get data linked to column
							const data = column.getValue(answers.item[column.name]);

							// return a string with linked name and corrosponding values
							return { name: `${column.linkedName} ${data[column.linkedName]}`, value: column };
						} else {
							// return a string with column names and corrosponding values
							return { name: `${column.name} ${answers.item[column.name]}`, value: column };
						}
					}).filter((choice) => {
						if (choice != null) return choice
						// filter nulls
					});

					return choice;
				}
			},
			{
				// ask this when column is not linked
				when: (answers) => { return (answers.column.linkedName === undefined) },
				type: "input",
				name: "newValue",
				message: (answers) => {
					let combinedName;
					if (answers.item.hasOwnProperty("name")) {
						combinedName = answers.item.name;
					} else {
						combinedName = `${answers.item.first_name} ${answers.item.last_name}`;
					}
					return `Enter new ${answers.column.name} for '${combinedName}'`
				}
			},
			{
				// ask this when column is linked
				when: (answers) => { return (answers.column.linkedName != undefined) },
				type: "list",
				name: "newValue",
				message: (answers) => {
					let combinedName;
					if (answers.item.hasOwnProperty("name")) {
						combinedName = answers.item.name;
					} else {
						combinedName = `${answers.item.first_name} ${answers.item.last_name}`;
					}
					return `Enter new ${answers.column.linkedName} for '${combinedName}'`
				},
				choices: (answers) => { return answers.column.getChoices() }
			}
		]

		const answers = await inquirer.prompt(questions);

		await table.updateItem(answers.item.id, answers.column.name, answers.newValue);
		table.displayItems();
	} catch (err) { throw err }
}

const deleteItem = async (tableName) => {
	try {
		const table = db.getTable(tableName);

		const questions = [
			{
				// ask which data item to modify
				type: "list",
				name: "item",
				message: `Which ${tableName.slice(0, -1)} to delete?`,
				choices: () => {
					return table.getItemsArray().map((item) => {
						let combinedName;
						if (item.hasOwnProperty("name")) {
							combinedName = item.name;
						} else {
							combinedName = `${item.first_name} ${item.last_name}`;
						}
						return { name: combinedName, value: item }
					});
				}
			},
		]

		const answers = await inquirer.prompt(questions);

		await table.deleteItem(answers.item.id);
		table.displayItems();
	} catch (err) {
		console.log(err)
		// console.log(`failed to delete ${}`)
	}
}

module.exports = { viewItems, addItem, updateItem, deleteItem }